// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {httpapi} from '../models';

export function Begin(arg1:main.beginRequest):Promise<Record<string, any>>;

export function ClusterDiagnostics():Promise<Record<string, any>>;

export function ClusterGroups():Promise<Record<string, any>>;

export function ClusterNodeStatus():Promise<Record<string, any>>;

export function ClusterStatus(arg1:string):Promise<Record<string, any>>;

export function Commit(arg1:main.txRequest):Promise<Record<string, any>>;

export function Domains():Promise<Record<string, any>>;

export function EngineStats():Promise<Record<string, any>>;

export function EntityVersionHistory(arg1:main.entityVersionHistoryRequest):Promise<Record<string, any>>;

export function Execute(arg1:main.executeRequest):Promise<Record<string, any>>;

export function ExecuteBatch(arg1:main.executeBatchRequest):Promise<Record<string, any>>;

export function Explain(arg1:main.explainRequest):Promise<Record<string, any>>;

export function FixtureExport(arg1:main.fixtureExportRequest):Promise<Record<string, any>>;

export function FixtureLoad(arg1:string):Promise<Record<string, any>>;

export function FixtureValidate(arg1:string):Promise<Record<string, any>>;

export function Health():Promise<Record<string, any>>;

export function PickFixtureExportFile(arg1:string):Promise<string>;

export function PickFixtureFile():Promise<string>;

export function ReadQuery(arg1:main.readQueryRequest):Promise<main.readQueryResponse>;

export function ReadRoutingStats():Promise<Record<string, any>>;

export function RecoveryBackupManifest(arg1:string):Promise<Record<string, any>>;

export function RecoveryCreateBackup(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RecoveryDefaults():Promise<Record<string, any>>;

export function RecoveryRestoreLSN(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function RecoveryRestoreTimestamp(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function RecoverySnapshotCatalog(arg1:string):Promise<Record<string, any>>;

export function RecoveryVerifyBackup(arg1:string):Promise<Record<string, any>>;

export function RecoveryWALRetention(arg1:string):Promise<Record<string, any>>;

export function ReplicationLag():Promise<Record<string, any>>;

export function ReplicationLastLSN():Promise<Record<string, any>>;

export function Rollback(arg1:main.txRequest):Promise<Record<string, any>>;

export function RowHistory(arg1:main.rowHistoryRequest):Promise<Record<string, any>>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function ScanStrategyStats():Promise<Record<string, any>>;

export function SchemaApply(arg1:main.schemaDDLRequest):Promise<Record<string, any>>;

export function SchemaApplySafeDiff(arg1:main.schemaDiffRequest):Promise<Record<string, any>>;

export function SchemaApplyStatements(arg1:main.schemaApplyStatementsRequest):Promise<Record<string, any>>;

export function SchemaDDL(arg1:main.schemaDDLRequest):Promise<Record<string, any>>;

export function SchemaDiff(arg1:main.schemaDiffRequest):Promise<Record<string, any>>;

export function SchemaLoadAllBaselines():Promise<Record<string, any>>;

export function SchemaLoadBaseline(arg1:main.schemaLoadBaselineRequest):Promise<Record<string, any>>;

export function SchemaTables(arg1:string):Promise<Record<string, any>>;

export function TemporalLookup(arg1:main.temporalLookupRequest):Promise<Record<string, any>>;

export function TimeTravel(arg1:main.timeTravelRequest):Promise<Record<string, any>>;

export function TimelineCommits(arg1:httpapi.TimelineCommitsRequest):Promise<Record<string, any>>;
