// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Begin(arg1) {
  return window['go']['main']['App']['Begin'](arg1);
}

export function ClusterDiagnostics() {
  return window['go']['main']['App']['ClusterDiagnostics']();
}

export function ClusterGroups() {
  return window['go']['main']['App']['ClusterGroups']();
}

export function ClusterNodeStatus() {
  return window['go']['main']['App']['ClusterNodeStatus']();
}

export function ClusterStatus(arg1) {
  return window['go']['main']['App']['ClusterStatus'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function Domains() {
  return window['go']['main']['App']['Domains']();
}

export function EngineStats() {
  return window['go']['main']['App']['EngineStats']();
}

export function EntityVersionHistory(arg1) {
  return window['go']['main']['App']['EntityVersionHistory'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function ExecuteBatch(arg1) {
  return window['go']['main']['App']['ExecuteBatch'](arg1);
}

export function Explain(arg1) {
  return window['go']['main']['App']['Explain'](arg1);
}

export function FixtureExport(arg1) {
  return window['go']['main']['App']['FixtureExport'](arg1);
}

export function FixtureLoad(arg1) {
  return window['go']['main']['App']['FixtureLoad'](arg1);
}

export function FixtureValidate(arg1) {
  return window['go']['main']['App']['FixtureValidate'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function PickFixtureExportFile(arg1) {
  return window['go']['main']['App']['PickFixtureExportFile'](arg1);
}

export function PickFixtureFile() {
  return window['go']['main']['App']['PickFixtureFile']();
}

export function ReadQuery(arg1) {
  return window['go']['main']['App']['ReadQuery'](arg1);
}

export function ReadRoutingStats() {
  return window['go']['main']['App']['ReadRoutingStats']();
}

export function RecoveryBackupManifest(arg1) {
  return window['go']['main']['App']['RecoveryBackupManifest'](arg1);
}

export function RecoveryCreateBackup(arg1, arg2) {
  return window['go']['main']['App']['RecoveryCreateBackup'](arg1, arg2);
}

export function RecoveryDefaults() {
  return window['go']['main']['App']['RecoveryDefaults']();
}

export function RecoveryRestoreLSN(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecoveryRestoreLSN'](arg1, arg2, arg3);
}

export function RecoveryRestoreTimestamp(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecoveryRestoreTimestamp'](arg1, arg2, arg3);
}

export function RecoverySnapshotCatalog(arg1) {
  return window['go']['main']['App']['RecoverySnapshotCatalog'](arg1);
}

export function RecoveryVerifyBackup(arg1) {
  return window['go']['main']['App']['RecoveryVerifyBackup'](arg1);
}

export function RecoveryWALRetention(arg1) {
  return window['go']['main']['App']['RecoveryWALRetention'](arg1);
}

export function ReplicationLag() {
  return window['go']['main']['App']['ReplicationLag']();
}

export function ReplicationLastLSN() {
  return window['go']['main']['App']['ReplicationLastLSN']();
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function RowHistory(arg1) {
  return window['go']['main']['App']['RowHistory'](arg1);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['main']['App']['SaveBinaryFile'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function ScanStrategyStats() {
  return window['go']['main']['App']['ScanStrategyStats']();
}

export function SchemaApply(arg1) {
  return window['go']['main']['App']['SchemaApply'](arg1);
}

export function SchemaApplySafeDiff(arg1) {
  return window['go']['main']['App']['SchemaApplySafeDiff'](arg1);
}

export function SchemaApplyStatements(arg1) {
  return window['go']['main']['App']['SchemaApplyStatements'](arg1);
}

export function SchemaDDL(arg1) {
  return window['go']['main']['App']['SchemaDDL'](arg1);
}

export function SchemaDiff(arg1) {
  return window['go']['main']['App']['SchemaDiff'](arg1);
}

export function SchemaLoadAllBaselines() {
  return window['go']['main']['App']['SchemaLoadAllBaselines']();
}

export function SchemaLoadBaseline(arg1) {
  return window['go']['main']['App']['SchemaLoadBaseline'](arg1);
}

export function SchemaTables(arg1) {
  return window['go']['main']['App']['SchemaTables'](arg1);
}

export function TemporalLookup(arg1) {
  return window['go']['main']['App']['TemporalLookup'](arg1);
}

export function TimeTravel(arg1) {
  return window['go']['main']['App']['TimeTravel'](arg1);
}

export function TimelineCommits(arg1) {
  return window['go']['main']['App']['TimelineCommits'](arg1);
}
