// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/asql/v1/raft.proto

package asqlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftRequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRequestVoteRequest) Reset() {
	*x = RaftRequestVoteRequest{}
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRequestVoteRequest) ProtoMessage() {}

func (x *RaftRequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RaftRequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_asql_v1_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftRequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftRequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RaftRequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RaftRequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RaftRequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRequestVoteResponse) Reset() {
	*x = RaftRequestVoteResponse{}
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRequestVoteResponse) ProtoMessage() {}

func (x *RaftRequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RaftRequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_asql_v1_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RaftRequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftRequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type RaftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEntry) Reset() {
	*x = RaftEntry{}
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEntry) ProtoMessage() {}

func (x *RaftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEntry.ProtoReflect.Descriptor instead.
func (*RaftEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_asql_v1_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RaftEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftEntry) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *RaftEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RaftEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RaftAppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*RaftEntry           `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAppendEntriesRequest) Reset() {
	*x = RaftAppendEntriesRequest{}
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAppendEntriesRequest) ProtoMessage() {}

func (x *RaftAppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*RaftAppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_asql_v1_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RaftAppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftAppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RaftAppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *RaftAppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *RaftAppendEntriesRequest) GetEntries() []*RaftEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RaftAppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type RaftAppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	LastIndex     uint64                 `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	ConflictTerm  uint64                 `protobuf:"varint,4,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	ConflictIndex uint64                 `protobuf:"varint,5,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAppendEntriesResponse) Reset() {
	*x = RaftAppendEntriesResponse{}
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAppendEntriesResponse) ProtoMessage() {}

func (x *RaftAppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asql_v1_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*RaftAppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_asql_v1_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RaftAppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftAppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RaftAppendEntriesResponse) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *RaftAppendEntriesResponse) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *RaftAppendEntriesResponse) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

var File_api_proto_asql_v1_raft_proto protoreflect.FileDescriptor

const file_api_proto_asql_v1_raft_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/asql/v1/raft.proto\x12\aasql.v1\"\x99\x01\n" +
	"\x16RaftRequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\"P\n" +
	"\x17RaftRequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"x\n" +
	"\tRaftEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xe8\x01\n" +
	"\x18RaftAppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12,\n" +
	"\aentries\x18\x05 \x03(\v2\x12.asql.v1.RaftEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x04R\fleaderCommit\"\xb4\x01\n" +
	"\x19RaftAppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"last_index\x18\x03 \x01(\x04R\tlastIndex\x12#\n" +
	"\rconflict_term\x18\x04 \x01(\x04R\fconflictTerm\x12%\n" +
	"\x0econflict_index\x18\x05 \x01(\x04R\rconflictIndex2\xb7\x01\n" +
	"\vRaftService\x12P\n" +
	"\vRequestVote\x12\x1f.asql.v1.RaftRequestVoteRequest\x1a .asql.v1.RaftRequestVoteResponse\x12V\n" +
	"\rAppendEntries\x12!.asql.v1.RaftAppendEntriesRequest\x1a\".asql.v1.RaftAppendEntriesResponseB\x1fZ\x1dasql/api/proto/asql/v1;asqlv1b\x06proto3"

var (
	file_api_proto_asql_v1_raft_proto_rawDescOnce sync.Once
	file_api_proto_asql_v1_raft_proto_rawDescData []byte
)

func file_api_proto_asql_v1_raft_proto_rawDescGZIP() []byte {
	file_api_proto_asql_v1_raft_proto_rawDescOnce.Do(func() {
		file_api_proto_asql_v1_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_asql_v1_raft_proto_rawDesc), len(file_api_proto_asql_v1_raft_proto_rawDesc)))
	})
	return file_api_proto_asql_v1_raft_proto_rawDescData
}

var file_api_proto_asql_v1_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_asql_v1_raft_proto_goTypes = []any{
	(*RaftRequestVoteRequest)(nil),    // 0: asql.v1.RaftRequestVoteRequest
	(*RaftRequestVoteResponse)(nil),   // 1: asql.v1.RaftRequestVoteResponse
	(*RaftEntry)(nil),                 // 2: asql.v1.RaftEntry
	(*RaftAppendEntriesRequest)(nil),  // 3: asql.v1.RaftAppendEntriesRequest
	(*RaftAppendEntriesResponse)(nil), // 4: asql.v1.RaftAppendEntriesResponse
}
var file_api_proto_asql_v1_raft_proto_depIdxs = []int32{
	2, // 0: asql.v1.RaftAppendEntriesRequest.entries:type_name -> asql.v1.RaftEntry
	0, // 1: asql.v1.RaftService.RequestVote:input_type -> asql.v1.RaftRequestVoteRequest
	3, // 2: asql.v1.RaftService.AppendEntries:input_type -> asql.v1.RaftAppendEntriesRequest
	1, // 3: asql.v1.RaftService.RequestVote:output_type -> asql.v1.RaftRequestVoteResponse
	4, // 4: asql.v1.RaftService.AppendEntries:output_type -> asql.v1.RaftAppendEntriesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_asql_v1_raft_proto_init() }
func file_api_proto_asql_v1_raft_proto_init() {
	if File_api_proto_asql_v1_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_asql_v1_raft_proto_rawDesc), len(file_api_proto_asql_v1_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_asql_v1_raft_proto_goTypes,
		DependencyIndexes: file_api_proto_asql_v1_raft_proto_depIdxs,
		MessageInfos:      file_api_proto_asql_v1_raft_proto_msgTypes,
	}.Build()
	File_api_proto_asql_v1_raft_proto = out.File
	file_api_proto_asql_v1_raft_proto_goTypes = nil
	file_api_proto_asql_v1_raft_proto_depIdxs = nil
}
